services:
  app:
    container_name: app
    image: mwazovzky/telegrambot-assistant
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_ASSIGNED_CHATS: ${TELEGRAM_ASSIGNED_CHATS}
      
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_EXPIRATION_TIME: ${REDIS_EXPIRATION_TIME}
      
      OPENAI_API_URL: ${OPENAI_API_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_ASSISTANT_NAME: ${OPENAI_ASSISTANT_NAME}

  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
